-- liquibase formatted sql

-- changeset Andrey:1

CREATE TABLE if not exists t1_kafka.metrics
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    description VARCHAR(1000),
    base_unit VARCHAR(200),
    statistic VARCHAR,
    value real
);