-- liquibase formatted sql

-- changeset Andrey:1

CREATE TABLE t1_kafka.metrics
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description VARCHAR(1000),
    date TIMESTAMP,

    name_id     BIGINT REFERENCES metric_names (id) NOT NULL,
    base_unit_id    BIGINT REFERENCES base_unit_names (id)
);